<?php

/**
 * BookTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BookTable
     */ 
  public static function getInstance()
    {
        return Doctrine_Core::getTable('Book');
    }
  public function createQueryI18N($alias = 'e', $culture = null)
  {
    if (!$culture) $culture = sfContext::getInstance()->getUser()->getCulture();
    return $this->createQuery($alias)
      ->innerJoin($alias . '.Translation t with t.book_name <> "" and t.lang = ?', $culture);
  }

  public function getForSitemap()
  {
    return $this->createQuery('e')
            ->select('e.id, t.id')
            ->leftJoin('e.Translation t')
            ->orderBy('e.id DESC')
            ->fetchArray();
  }

  public function getObjectItem($params)
  {
    return $this->createQueryI18N('e', $params['sf_culture'])
      ->andWhere('e.id = ?', $params['id'])
      ->fetchOne();
  }

  public function retrieveBackendObjectList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias.'.Translation t WITH t.lang = ?', 'ru');

    return $q;
  }
  
  public function getAuthors() 
  {
    return $this->createQueryI18N()->select('e.id, t.author')->groupBy('author')->orderBy('author')->setHydrationMode(Doctrine::HYDRATE_ARRAY_SHALLOW)->execute();
  }
  
  public function getPublisher() 
  {
    return $this->createQueryI18N()->select('e.id, t.publishing_house')->groupBy('publishing_house')->orderBy('publishing_house')->setHydrationMode(Doctrine::HYDRATE_ARRAY_SHALLOW)->execute();
  }
  
  public function getPublicationYears() 
  {
    return $this->createQueryI18N()->select('e.id, t.publication_date')->groupBy('publication_date')->orderBy('publication_date')->setHydrationMode(Doctrine::HYDRATE_ARRAY_SHALLOW)->execute();
  }
  
  
    
}