<?php

/**
 * BookImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BookImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BookImage');
    }
    
}