<?php

/**
 * Feedback
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    garage
 * @subpackage model
 * @author     Garin Studio <eugeniy.b@garin-studio.ru>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Feedback extends BaseFeedback
{
}
