<?php

/**
 * GalleryImageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GalleryImageTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object GalleryImageTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('GalleryImage');
  }


  public function getRelatedImages($gallery_id)
  {
    return $this->createQuery('i')
            ->leftJoin('i.Translation t')
            ->where('i.gallery_id = ?', $gallery_id)
            ->execute();
  }
}