<?php

/**
 * LetterTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LetterTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object LetterTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Letter');
  }
}