<?php

/**
 * NewsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object NewsTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('News');
  }


  public function createQueryI18N($alias = 'n', $culture = null)
  {
    if (!$culture) $culture = sfContext::getInstance()->getUser()->getCulture();
    return $this->createQuery($alias)
            ->innerJoin($alias.'.Translation t WITH t.lang = ?', $culture);
  }

  public function getForSitemap()
  {
    return $this->createQuery('n')
            ->select('n.id, t.id')
            ->leftJoin('n.Translation t')
            ->orderBy('n.id DESC')
            ->fetchArray();
  }

  public function getObjectItem($params)
  {
    return $this->createQueryI18N('n', $params['sf_culture'])
            ->andWhere('n.id = ?', $params['id'])
            ->fetchOne();
  }

  public function retrieveBackendObjectList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias.'.Translation t WITH t.lang = ?', 'ru');

    return $q;
  }
}