<?php

/**
 * News
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    garage
 * @subpackage model
 * @author     Garin Studio <eugeniy.b@garin-studio.ru>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class News extends BaseNews
{
  private $_preview_file, $_banner_file, $_images_delete;


  /**
   * @return FileStorage
   */
  protected function getStorage($prefix = 'news_preview')
  {
    if (!$this->id) {
      throw new Exception('Unable to get storage for unsaved instance');
    }

    return new FileStorage(array(
      'level'       => 1,
      'prefix'      => $prefix,
    ));
  }

  public function cleanPath($path)
  {
    return str_replace(sfConfig::get('sf_web_dir'), '', $path);
  }


  public function getPreviewImage()
  {
    return $this->id ? $this->cleanPath($this->getStorage()->getFilename($this->id)) : false;
  }

  public function getPreviewImageMedium()
  {
    return $this->cleanPath($this->getStorage('news_preview')->getThumb(
      $this->id, 'news_preview_medium', array('width' => 590), 'news_preview'
    ));
  }
  public function getPreviewImageThumb()
  {
    return $this->cleanPath($this->getStorage('news_preview')->getThumb(
      $this->id, 'news_preview_thumb', array('width' => 279), 'news_preview'
    ));
  }

  public function setPreviewImage($value)
  {
    if ($value instanceOf sfValidatedFile) {
      $this->_preview_file = $value;
    }
  }


  public function save(Doctrine_Connection $conn = null)
  {
    parent::save($conn);

    if ($this->_preview_file instanceOf sfValidatedFile) {
      $storage = $this->getStorage();
      $storage->delete($this->id);
      $storage->delete($this->id, 'news_preview_thumb');
      $storage->delete($this->id, 'news_preview_medium');

      $storage->buildPath($this->id);
      $target = $storage->generateFilename($this->id, null, $this->_preview_file->getOriginalName());
      $this->_preview_file->save($target);
    }
    elseif (false === $this->$fname) {
      $storage = $this->getStorage()->delete($this->id);
    }
    $this->_preview_file = null;

    $this->updateSearchIndex();
  }

  public function delete(Doctrine_Connection $conn = null)
  {
    parent::delete($conn);
    foreach (array('news_preview', 'news_preview_medium', 'news_preview_thumb') as $prefix) {
      $this->getStorage($prefix)->delete($this->id);
    }
    Search::delete($this);
  }


  public function updateSearchIndex()
  {
    foreach (sfConfig::get('sf_languages') as $lang) {
      if (!$this->Translation[$lang]->title) {
        continue;
      }

      $doc = Search::createDocument($this);
      $doc->addField(Zend_Search_Lucene_Field::text('title', $this->Translation[$lang]->title));
      $doc->addField(Zend_Search_Lucene_Field::text(
        'contents', Search::cleanText(
          $this->Translation[$lang]->short,
          $this->Translation[$lang]->full
        )
      ));

      $doc->getField('title')->boost = 5;
      $doc->getField('contents')->boost = 1;

      Search::getInstance($lang)->addDocument($doc);
    }
  }
}
