<?php

/**
 * PageImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PageImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PageImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PageImage');
    }
}