<?php

/**
 * ReservationTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReservationTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ReservationTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Reservation');
  }

  public function retrieveBackendObjectList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias.'.Event e')
            ->leftJoin('e.Translation t WITH t.lang = ?', 'ru');

    return $q;
  }
}