<?php

/**
 * VideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Video');
    }
    
    public function createQueryI18N($alias = 'v', $culture = null)
    {
      if (!$culture) $culture = sfContext::getInstance()->getUser()->getCulture();
      return $this->createQuery($alias)
        ->innerJoin($alias . '.Translation t with t.title <> "" and t.lang = ?', $culture);
    }


    public function getObjectItem($params)
    {
      return $this->createQueryI18N('v', $params['sf_culture'])
        ->andWhere('v.id = ?', $params['id'])
        ->fetchOne();
    }

    public function retrieveBackendObjectList(Doctrine_Query $q)
    {
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias.'.Translation t WITH t.lang = ?', 'ru');

      return $q;
    }
}