<?php

/**
 * Video
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    garage
 * @subpackage model
 * @author     Garin Studio <eugeniy.b@garin-studio.ru>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Video extends BaseVideo
{
  
   public function save(Doctrine_Connection $conn = null)
  {
    $en_modified = $this->Translation['en']->getModified();    

    parent::save($conn);
    
    $this->updateSearchIndex();
  }
  
  public function updateSearchIndex()
  {
    foreach (sfConfig::get('sf_languages') as $lang) {
      if (!$this->Translation[$lang]->title) {
        continue;
      }

      $doc = Search::createDocument($this);
      $doc->addField(Zend_Search_Lucene_Field::text('title', $this->Translation[$lang]->title));
      

      $doc->getField('title')->boost = 5;

      Search::getInstance($lang)->addDocument($doc);
    }
  }
}
