all:
  .array:
    options:
      allowed_symbols:  23456789abcdeghkmnpqsuvxyz
      length:           4
      width:            100,
      height:           40,
      credits:          ~
      foreground:       [50, 50, 50]
      background:       [255, 255, 255]