generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GalleryImage
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gallery_image
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~

      form:
        display: [ru, en]
        actions: { _save: ~ }

      edit:
        title: Редактирование изображения
        
      new:     ~
