<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('feedback', 'is_answered', 'boolean', '25', array(
             'default' => '0',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('feedback', 'is_answered');
    }
}