<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base {

  public function up() {
    $this->createTable('user', array(
      'id' =>
      array(
        'type' => 'integer',
        'unsigned' => '1',
        'primary' => '1',
        'autoincrement' => '1',
        'length' => '2',
      ),
      'group' =>
      array(
        'type' => 'enum',
        'values' =>
        array(
          0 => 'PRESS',
          1 => 'MEMBER',
        ),
        'notnull' => '1',
        'length' => '',
      ),
      'fio' =>
      array(
        'type' => 'string',
        'notnull' => '1',
        'length' => '150',
      ),
      'email' =>
      array(
        'type' => 'string',
        'email' =>
        array(
          'check_mx' => '',
        ),
        'notnull' => '1',
        'unique' => '1',
        'length' => '50',
      ),
      'password' =>
      array(
        'type' => 'string',
        'fixed' => '1',
        'notnull' => '1',
        'length' => '40',
      ),
      'token' =>
      array(
        'type' => 'string',
        'fixed' => '1',
        'length' => '16',
      ),
      'created_at' =>
      array(
        'notnull' => '1',
        'type' => 'timestamp',
        'length' => '25',
      ),
            ), array(
      'type' => 'InnoDB',
      'primary' =>
      array(
        0 => 'id',
      ),
      'collate' => 'utf8_general_ci',
      'charset' => 'utf8',
    ));
  }

  public function down() {
    $this->dropTable('user');
  }

}