<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('reservation', 'reservation_event_id_event_id', array(
             'name' => 'reservation_event_id_event_id',
             'local' => 'event_id',
             'foreign' => 'id',
             'foreignTable' => 'event',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->addIndex('reservation', 'reservation_event_id', array(
             'fields' => 
             array(
              0 => 'event_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('reservation', 'reservation_event_id_event_id');
        $this->removeIndex('reservation', 'reservation_event_id', array(
             'fields' => 
             array(
              0 => 'event_id',
             ),
             ));
    }
}