<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('subscriber', 'email', 'string', '50', array(
             'notnull' => '1',
             'unique' => '1',
             'email' => '1',
             ));
    }

    public function down()
    {
        $this->changeColumn('subscriber', 'email', 'string', '50', array(
             'notnull' => '1',
             'email' => '1',
             ));
    }
}