<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version31 extends Doctrine_Migration_Base
{
    public function up()
    {        
        $this->createTable('book_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'length' => '4',
              'primary' => '1',
             ),
             'book_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'author' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'publishing_house' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'about_book' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'about_author' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'about_publishing' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'publication_date' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'price' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'contacts' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'work_time' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'html_code' => 
             array(
              'type' => 'clob',
              'length' => '1024',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
		$this->createForeignKey('book_translation', 'book_translation_id_book_id', array(
             'name' => 'book_translation_id_book_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'book',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
		$this->addIndex('book_translation', 'book_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('book_translation');
		$this->dropForeignKey('book_translation', 'book_translation_id_book_id');
		$this->removeIndex('book_translation', 'book_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}