<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version37 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('note_translation');
        $this->addColumn('note', 'name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('note', 'event_name', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->createTable('note_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'length' => '4',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'event_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('note', 'name');
        $this->removeColumn('note', 'event_name');
    }
}