<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version35 extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->removeColumn('note', 'ordering');
      $this->addColumn('note', 'position', 'integer', 8);
    }

    public function down()
    {
      $this->removeColumn('note', 'position');
    }
}