<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version34 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('note_translation', 'note_translation_id_note_id', array(
             'name' => 'note_translation_id_note_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'note',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('note_translation', 'note_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('note_translation', 'note_translation_id_note_id');
        $this->removeIndex('note_translation', 'note_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}