<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version40 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('video_translation', 'video_translation_id_video_id', array(
             'name' => 'video_translation_id_video_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'video',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('video_translation', 'video_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('video_translation', 'video_translation_id_video_id');
        $this->removeIndex('video_translation', 'video_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}