<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version41 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('event', 'on_prehistory', 'boolean', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('event', 'on_education_prog', 'boolean', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('event', 'on_prehistory');
        $this->removeColumn('event', 'on_education_prog');
    }
}