<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version42 extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->changeColumn('event', 'date_start', 'date', 25);
    $this->changeColumn('event_translation', 'short', 'string', 255);

    $this->addColumn('event', 'published_at', 'timestamp', 25);

    $this->addIndex('event', 'published', array(
      'fields' => array('published_at'),
    ));
  }

  public function postUp()
  {
    parent::postUp();

    Doctrine_Manager::connection()->exec('UPDATE `event` SET `published_at` = NOW()');
  }

  public function down()
  {
    $this->removeColumn('event', 'published_at');
  }
}
