<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version45 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('page_image', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '2',
             ),
             'page_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '1',
              'length' => '2',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        
        $this->createForeignKey('page_image', 'page_image_page_id_page_id', array(
             'name' => 'page_image_page_id_page_id',
             'local' => 'page_id',
             'foreign' => 'id',
             'foreignTable' => 'page',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->addIndex('page_image', 'page_image_page_id', array(
             'fields' => 
             array(
              0 => 'page_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('page_image', 'page_image_page_id_page_id');
        $this->removeIndex('page_image', 'page_image_page_id', array(
             'fields' => 
             array(
              0 => 'page_id',
             ),
             ));
      
        $this->dropTable('page_image');
    }
}