options:
  type: InnoDB
  collate: utf8_general_ci
  charset: utf8
detect_relations: false

News:
  actAs:
    I18n:
      fields: [title, short, full]

  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    date:
      type: date
      notnull: true

    gallery_id:
      type: integer(4)
      unsigned: true

    title:
      type: string(255)
      notnull: true
    short:
      type: string(255)
      notnull: true
    full: string

  relations:
    Gallery:
      type: one
      foreignType: one
      onDelete: set null


Page:
  actAs:
    NestedSet: ~
    I18n:
      fields: [title, h1, body, seo_title, seo_description]

  columns:
    id:
      type: integer(2)
      unsigned: true
      primary: true
      autoincrement: true
    title:
      type: string(255)
      notnull: true
    h1: string(255)
    body: clob(16777215)
    seo_title: string(255)
    seo_description: string(255)
    slug:
      type: string(255)
      notnull: true
      unique: true
      
PageImage:
  columns:
    id:
      type: integer(2)
      unsigned: true
      primary: true
      autoincrement: true
    page_id:
      type: integer(2)
      unsigned: true
      notnull: true

  relations:
    Page:
      type: one
      foreignType: many
      foreignAlias: Images
      onDelete: cascade
